### ISSUE TITLE
RO ID clash

### ISSUE THREAD

**Issue by linikujp** [CLO-ontology/CLO#10]
<a href="https://github.com/GoogleCodeExporter"><img src="https://avatars.githubusercontent.com/u/9614759?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [GoogleCodeExporter](https://github.com/GoogleCodeExporter)**
_Tuesday May 12, 2015 at 11:44 GMT_
_Originally opened as https://github.com/linikujp/clo-ontology/issues/10_

---

```
RO_0002000 'boundary of' and RO_0002002 'has boundary' are being reused for 
other terms in CLO

http://www.ontobee.org/browser/rdf.php?o=CLO&iri=http://purl.obolibrary.org/obo/
RO_0002000 'capable of part of'
http://www.ontobee.org/browser/rdf.php?o=CLOt&iri=http://purl.obolibrary.org/obo
/RO_0002002 'has function in part of'

'capable of part of' ID should be RO_0002216.  'has function in part of' could 
almost certainly be safely mapped to the same relation.

Note - first reported here: 
https://sourceforge.net/p/obo/mailman/message/33261369/


```

Original issue reported on code.google.com by `dosu...@gmail.com` on 23 Jan 2015 at 5:20

**Comment by yongqunh** [comment]
This bug does not exist any more.
