### ISSUE TITLE
293 cell should be HEK293 cell

### ISSUE THREAD

**Issue by linikujp** [CLO-ontology/CLO#12]
<a href="https://github.com/GoogleCodeExporter"><img src="https://avatars.githubusercontent.com/u/9614759?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [GoogleCodeExporter](https://github.com/GoogleCodeExporter)**
_Tuesday May 12, 2015 at 11:44 GMT_
_Originally opened as https://github.com/linikujp/clo-ontology/issues/12_

---

```
CLO_0001230 should be updated
293 cell is equal to HEK 293 cell(BTO_0000007;EFO_0001182)

```

Original issue reported on code.google.com by `linik...@gmail.com` on 29 Apr 2015 at 2:11

**Comment by yongqunh** [comment]
They are synonyms now:
http://purl.obolibrary.org/obo/CLO_0001230
