### ISSUE TITLE
Error when loading CLO

### ISSUE THREAD

**Issue by siiraa** [CLO-ontology/CLO#16]
here is the log:

Error 1 Logged at Mon Jun 22 13:40:11 BST 2015
IOException: Bad ontology library declaration - check logs. Warnings now disabled for this session.
    org.protege.editor.owl.model.library.folder.FolderGroupManager.isSuitable(FolderGroupManager.java:123)
    org.protege.editor.owl.model.library.OntologyCatalogManager.update(OntologyCatalogManager.java:158)
    org.protege.editor.owl.model.library.OntologyCatalogManager.ensureCatalogExists(OntologyCatalogManager.java:116)
    org.protege.editor.owl.model.library.OntologyCatalogManager.addFolder(OntologyCatalogManager.java:189)
    org.protege.editor.owl.model.OWLModelManagerImpl.addRootFolder(OWLModelManagerImpl.java:353)
    org.protege.editor.owl.model.OWLModelManagerImpl.loadOntologyFromPhysicalURI(OWLModelManagerImpl.java:309)
    org.protege.editor.owl.OWLEditorKit.handleLoadFrom(OWLEditorKit.java:190)
    org.protege.editor.core.ProtegeManager.loadAndSetupEditorKitFromURI(ProtegeManager.java:207)
    org.protege.editor.core.ProtegeApplication.editURI(ProtegeApplication.java:499)
    org.protege.editor.core.platform.apple.ProtegeAppleApplication.editFile(ProtegeAppleApplication.java:67)
    org.protege.editor.core.platform.apple.AbstractAppleApplicationWrapper$1.invoke(AbstractAppleApplicationWrapper.java:141)
    com.sun.proxy.$Proxy0.handleOpenFile(Unknown Source)
    com.apple.eawt._AppEventLegacyHandler$5.dispatchEvent(_AppEventLegacyHandler.java:122)
    com.apple.eawt._AppEventLegacyHandler.sendEventToEachListenerUntilHandled(_AppEventLegacyHandler.java:168)
    com.apple.eawt._AppEventLegacyHandler.openFiles(_AppEventLegacyHandler.java:120)
    com.apple.eawt._AppEventHandler$_OpenFileDispatcher.performUsing(_AppEventHandler.java:353)
    com.apple.eawt._AppEventHandler$_OpenFileDispatcher.performUsing(_AppEventHandler.java:344)
    com.apple.eawt._AppEventHandler$_AppEventDispatcher$1.run(_AppEventHandler.java:489)
    java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    java.awt.EventQueue.access$400(EventQueue.java:82)
    java.awt.EventQueue$2.run(EventQueue.java:676)
    java.awt.EventQueue$2.run(EventQueue.java:674)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)

**Comment by linikujp** [comment]
Is this issue resolved? If so, please close the issue.

**Comment by siiraa** [comment]
No, the issue has not been resolved. here is the log. It appears that CLO has some bad library declaration that is causing this error.

Error 1 Logged at Tue Jun 30 13:49:18 BST 2015
IOException: Bad ontology library declaration - check logs. Warnings now disabled for this session.
    org.protege.editor.owl.model.library.folder.FolderGroupManager.isSuitable(FolderGroupManager.java:123)
    org.protege.editor.owl.model.library.OntologyCatalogManager.update(OntologyCatalogManager.java:158)
    org.protege.editor.owl.model.library.OntologyCatalogManager.ensureCatalogExists(OntologyCatalogManager.java:116)
    org.protege.editor.owl.model.library.OntologyCatalogManager.addFolder(OntologyCatalogManager.java:189)
    org.protege.editor.owl.model.OWLModelManagerImpl.addRootFolder(OWLModelManagerImpl.java:353)
    org.protege.editor.owl.model.OWLModelManagerImpl.loadOntologyFromPhysicalURI(OWLModelManagerImpl.java:309)
    org.protege.editor.owl.OWLEditorKit.handleLoadFrom(OWLEditorKit.java:190)
    org.protege.editor.core.ProtegeManager.loadAndSetupEditorKitFromURI(ProtegeManager.java:207)
    org.protege.editor.core.ProtegeApplication.editURI(ProtegeApplication.java:499)
    org.protege.editor.core.platform.apple.ProtegeAppleApplication.editFile(ProtegeAppleApplication.java:67)
    org.protege.editor.core.platform.apple.AbstractAppleApplicationWrapper$1.invoke(AbstractAppleApplicationWrapper.java:141)
    com.sun.proxy.$Proxy0.handleOpenFile(Unknown Source)
    com.apple.eawt._AppEventLegacyHandler$5.dispatchEvent(_AppEventLegacyHandler.java:122)
    com.apple.eawt._AppEventLegacyHandler.sendEventToEachListenerUntilHandled(_AppEventLegacyHandler.java:168)
    com.apple.eawt._AppEventLegacyHandler.openFiles(_AppEventLegacyHandler.java:120)
    com.apple.eawt._AppEventHandler$_OpenFileDispatcher.performUsing(_AppEventHandler.java:353)
    com.apple.eawt._AppEventHandler$_OpenFileDispatcher.performUsing(_AppEventHandler.java:344)
    com.apple.eawt._AppEventHandler$_AppEventDispatcher$1.run(_AppEventHandler.java:489)
    java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    java.awt.EventQueue.access$400(EventQueue.java:82)
    java.awt.EventQueue$2.run(EventQueue.java:676)
    java.awt.EventQueue$2.run(EventQueue.java:674)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
—————————————————————————————————————————————————

**Comment by yongqunh** [comment]
Hi Sira,

Which reasoner did you use for this?

Oliver

**Comment by zhengj2007** [comment]
Hi Sira,

How did you load the CLO? I clone the project from Github and no problem to load the ontology using Protege 4.3.

**Comment by siiraa** [comment]
Hi, I use Hermit on 4.3.

**Comment by siiraa** [comment]
CLO BFO/RO imports are calling bad URIs. This is also failing CLO load-in at all EBI tools (ZOOMA, OLS). We are in the middle of releasing OLS3 and if CLO doesn't load/call the right BFO/RO URIs, it will not be loaded in ZOOMA nor OLS.

**Comment by zhengj2007** [comment]
Does it cause by the https protocol? Do you have issues to load BFO or OBI?

**Comment by siiraa** [comment]
We use OWLAPI loading CLO from the permanent url (purl.obofoundry.org/obo/clo.owl), not GITHUB. I'm checking out GITHUB version to see if the issues is coming from where.

**Comment by siiraa** [comment]
I tried removing CLO svn from my machine, re-checkout from Github, still receiving this error when opening clo.owl on protege 4.3 causing by bad ontology library declaration. When using OWLAPI to load CLO, the bad library declaration seemed to have come from BFO import (and possible RO).



Error 1 Logged at Tue Oct 13 16:05:00 BST 2015
IOException: Bad ontology library declaration - check logs. Warnings now disabled for this session.
    org.protege.editor.owl.model.library.folder.FolderGroupManager.isSuitable(FolderGroupManager.java:123)
    org.protege.editor.owl.model.library.OntologyCatalogManager.update(OntologyCatalogManager.java:158)
    org.protege.editor.owl.model.library.OntologyCatalogManager.ensureCatalogExists(OntologyCatalogManager.java:116)
    org.protege.editor.owl.model.library.OntologyCatalogManager.addFolder(OntologyCatalogManager.java:189)
    org.protege.editor.owl.model.OWLModelManagerImpl.addRootFolder(OWLModelManagerImpl.java:353)
    org.protege.editor.owl.model.OWLModelManagerImpl.loadOntologyFromPhysicalURI(OWLModelManagerImpl.java:309)
    org.protege.editor.owl.OWLEditorKit.handleLoadFrom(OWLEditorKit.java:190)
    org.protege.editor.core.ProtegeManager.loadAndSetupEditorKitFromURI(ProtegeManager.java:207)
    org.protege.editor.core.ProtegeApplication.editURI(ProtegeApplication.java:499)
    org.protege.editor.core.platform.apple.ProtegeAppleApplication.editFile(ProtegeAppleApplication.java:67)
    org.protege.editor.core.platform.apple.AbstractAppleApplicationWrapper$1.invoke(AbstractAppleApplicationWrapper.java:141)
    com.sun.proxy.$Proxy0.handleOpenFile(Unknown Source)
    com.apple.eawt._AppEventLegacyHandler$5.dispatchEvent(_AppEventLegacyHandler.java:122)
    com.apple.eawt._AppEventLegacyHandler.sendEventToEachListenerUntilHandled(_AppEventLegacyHandler.java:168)
    com.apple.eawt._AppEventLegacyHandler.openFiles(_AppEventLegacyHandler.java:120)
    com.apple.eawt._AppEventHandler$_OpenFileDispatcher.performUsing(_AppEventHandler.java:353)
    com.apple.eawt._AppEventHandler$_OpenFileDispatcher.performUsing(_AppEventHandler.java:344)
    com.apple.eawt._AppEventHandler$_AppEventDispatcher$1.run(_AppEventHandler.java:489)
    java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    java.awt.EventQueue.access$400(EventQueue.java:82)
    java.awt.EventQueue$2.run(EventQueue.java:676)
    java.awt.EventQueue$2.run(EventQueue.java:674)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
---------------------------------------------------------------------------------------------------

**Comment by zhengj2007** [comment]
purl.obofoundry.org/obo/clo.owl redirects to:
https://raw.githubusercontent.com/CLO-ontology/CLO/master/src/ontology/clo.owl

It imports following OWL files:
        <owl:imports rdf:resource="&obo;clo/BFO_import.owl"/>
        <owl:imports rdf:resource="&obo;clo/CL_import.owl"/>
        <owl:imports rdf:resource="&obo;clo/GO_import.owl"/>
        <owl:imports rdf:resource="&obo;clo/IAO_import.owl"/>
        <owl:imports rdf:resource="&obo;clo/NCBITaxon_import.owl"/>
        <owl:imports rdf:resource="&obo;clo/OBI_import.owl"/>
        <owl:imports rdf:resource="&obo;clo/PATO_import.owl"/>
        <owl:imports rdf:resource="&obo;clo/UBERON_import.owl"/>
        <owl:imports rdf:resource="&obo;clo/cellline_import.owl"/>
        <owl:imports rdf:resource="http://www.obofoundry.org/ro/ro.owl"/>

For those like &obo;clo/PATO_import.owl, the server will try to load file from: http://purl.obolibrary.org/obo/clo/PATO_import.owl. However, CLO does not set PURLs redirect for those files. They cannot be loaded since the files cannot be found. 

Can you set the CLO purls? If so, please set PURLs for following OWL files: 
        <owl:imports rdf:resource="&obo;clo/BFO_import.owl"/>
        <owl:imports rdf:resource="&obo;clo/CL_import.owl"/>
        <owl:imports rdf:resource="&obo;clo/GO_import.owl"/>
        <owl:imports rdf:resource="&obo;clo/IAO_import.owl"/>
        <owl:imports rdf:resource="&obo;clo/NCBITaxon_import.owl"/>
        <owl:imports rdf:resource="&obo;clo/OBI_import.owl"/>
        <owl:imports rdf:resource="&obo;clo/PATO_import.owl"/>
        <owl:imports rdf:resource="&obo;clo/UBERON_import.owl"/>
        <owl:imports rdf:resource="&obo;clo/cellline_import.owl"/>
You need to find out where these files located in the CLO github.

**Comment by siiraa** [comment]
I have this specific comment from Tony Burdett that RO is using the wrong URI
http://www.obofoundry.org/ro/ro.owl instead of http://purl.obolibrary.org/obo/ro.owl
although i'm not sure what the URI of the RO ontology is, actually

**Comment by siiraa** [comment]
Hi Jie,
Is your previous comment missing the links?

**Comment by zhengj2007** [comment]
Yes, \< and \> are special characters, I need add escape to make it visible on the page.

**Comment by zhengj2007** [comment]
What I am talking about is "the bad library declaration seemed to have come from BFO import". Need to set a purl for it.

**Comment by siiraa** [comment]
I am investigating src/ontology/external/ro.owl, i think this file may points to the wrong namespace

**Comment by zhengj2007** [comment]
If you use http://purl.obolibrary.org/obo/ro.owl, you can ignore src/ontology/external/ro.owl. However, it might be different since RO makes many changes lately.

**Comment by siiraa** [comment]
ro.owl seems alright. I wonder where the 'www.obofoundry.org/obo/ro.owl' come from. I see that in the import declaration in clo.owl. I'm looking at clo.owl now

**Comment by zhengj2007** [comment]
www.obofoundry.org/obo/ro.owl is the old PURL setting of RO.

**Comment by siiraa** [comment]
i've just updated that in clo.owl, seems to fix the problem but I keep getting "org.xml.sax.SAXParseException: White spaces are required between publicId and systemId." and everytime I see this error, I just don't know where to fix it? Any idea?

**Comment by zhengj2007** [comment]
After you checking out CLO from github, you should be able to open it correctly using Protege 5 beta since http://purl.obolibrary.org/obo/ro.owl redirects to https://raw.githubusercontent.com/oborel/obo-relations/master/ro.owl. Protege 4.3 cannot handle https protocol. 

You cannot open CLO from URL: http://purl.obofoundry.org/obo/clo.owl since it imports several OWL using invalid URL. If you set the PURLs for those files, it should work.

**Comment by zhengj2007** [comment]
error: "org.xml.sax.SAXParseException: White spaces are required between publicId and systemId" should be solved if you use Protege 5 beta.

**Comment by yongqunh** [comment]
Later we should try to link the CLO to a merged owl file instead of the unmerged owl file that imports many other owl files.

Oliver

**Comment by yongqunh** [comment]
This should not be an issue any more.
