### ISSUE TITLE
Purl redirect for x_import.owl is not functioning correctly

### ISSUE THREAD

**Issue by nzllim** [CLO-ontology/CLO#22]
Hi,

I attempted to load CLO.owl in Protege 5.0.0-b17 through the following URLs:
http://purl.obolibrary.org/obo/clo.owl
https://raw.githubusercontent.com/CLO-ontology/CLO/master/src/ontology/clo.owl

However, Protege is unable to resolve the redirects for the various imports you use (e.g. PATO, CL etc...)

Protege attempts to look for (say PATO_import.owl) at http://purl.obolibrary.org/obo/clo/PATO_import.owl, which doesn't exist.

Thanks for looking into this.

Nathaniel

**Comment by linikujp** [comment]
Hi Nathaniel,

Did you also downloaded the PATO_import.owl from the github?
The CLO is constructed with all imports files including terms from other ontologies.

Please check out the clo_merged.owl listed in this page : https://github.com/CLO-ontology/CLO/tree/master/src/ontology
Or here: https://raw.githubusercontent.com/CLO-ontology/CLO/master/src/ontology/clo_merged.owl
to get the merged file, where there is no need to import other OWL files. 

Thanks,
Asiyah

**Comment by nzllim** [comment]
Hi Asiyah,

I tested CLO.owl mainly because our lab's analysis platform was having issues in loading the ontology. I did not manually download all the other ?_import.owl to mimic actual use...

clo_merged.owl works on Protege. Thank you for the suggestion.

Regards,
Nathaniel
