### ISSUE TITLE
[LINCS] SK-MES

### ISSUE THREAD

**Issue by chung88** [CLO-ontology/CLO#29]
The difference is the synonym
SK-MES; SK-MES-1; SK MES 1

Both have the same provider and catalog ID.
seeAlso: ATCC: HTB-58
seeAlso: HyperCLDB: cl4325; ATCC: HTB-58

http://www.ontobee.org/ontology/LINCS-CLOview?iri=http://purl.obolibrary.org/obo/CLO_0009048
http://www.ontobee.org/ontology/CLO?iri=http://purl.obolibrary.org/obo/CLO_0009049

**Comment by yongqunh** [comment]
effective: http://purl.obolibrary.org/obo/CLO_0009049
the other one is obsolete
