### ISSUE TITLE
BAE-BAO Cell Lines

### ISSUE THREAD

**Issue by handemcginty** [CLO-ontology/CLO#35]
https://drive.google.com/open?id=0B2oTJxSU7CWraEJUcW5BZ2xnT2s
Please see the document for the proposed cell lines from CDD for BAO.

**Comment by yongqunh** [comment]
Ensured that all these BAO cell lines are added:
Term ID	proposed term's name	PubChem AID
http://purl.obolibrary.org/obo/CLO_0037212	BJeLR	2635
http://purl.obolibrary.org/obo/CLO_0037213	BJeH	493051
http://purl.obolibrary.org/obo/CLO_0037214	RS-11846	743410
http://purl.obolibrary.org/obo/CLO_0037216	CHO-S	624379
http://purl.obolibrary.org/obo/CLO_0037217	DRD	2633
http://purl.obolibrary.org/obo/CLO_0037218	HL2/3	504574
http://purl.obolibrary.org/obo/CLO_0037219	HeLa-MAGI-CCR5	504341
http://purl.obolibrary.org/obo/CLO_0037220	HeLa-R5-16	504341
http://purl.obolibrary.org/obo/CLO_0037221	RD-HGA16	624467
http://purl.obolibrary.org/obo/CLO_0009047	SK-MEL-5	488899
http://purl.obolibrary.org/obo/CLO_0009905	SNB-75	652144
http://purl.obolibrary.org/obo/CLO_0037222	Sufu-KO-LIGHT	588413
http://purl.obolibrary.org/obo/CLO_0009215	SW403	504653
http://purl.obolibrary.org/obo/CLO_0037223	Ub-G76V-GFP/HeLa	463185
