### ISSUE TITLE
[LINCS] multiple CLO IDs per cell

### ISSUE THREAD

**Issue by chung88** [CLO-ontology/CLO#36]
The following list of cell names have more than one CLO ID.
For examples:
http://www.ontobee.org/search?ontology=LINCS-CLOview&keywords=BALL-1&submit=Search+terms
http://purl.obolibrary.org/obo/CLO_0051004 (CLO):
BALL-1 in Ontobee: LINCS-CLOview
http://purl.obolibrary.org/obo/CLO_0051005 (CLO):
BALL-1 in Ontobee: LINCS-CLOview

LIST (shared drive document  "LINCS_-all-Xrefs-Ontorat_input-processed.xlsx":
CLO_ID  cell name   CL_LINCS_ID
http://purl.obolibrary.org/obo/CLO_0051005  BALL-1  LCL-1005
http://purl.obolibrary.org/obo/CLO_0050970  NALM-6  LCL-1007
http://purl.obolibrary.org/obo/CLO_0050143  CCRF-CEM    LCL-1012
http://purl.obolibrary.org/obo/CLO_0050992  MOLT-4  LCL-1019
http://purl.obolibrary.org/obo/CLO_0008782  Reh LCL-1039
http://purl.obolibrary.org/obo/CLO_0050406  HCE-T   LCL-1047
http://purl.obolibrary.org/obo/CLO_0007094  KG-1    LCL-1056
http://purl.obolibrary.org/obo/CLO_0051561  KG-1a   LCL-1057
http://purl.obolibrary.org/obo/CLO_0050999  THP-1   LCL-1072
http://purl.obolibrary.org/obo/CLO_0050123  K-562   LCL-1103
http://purl.obolibrary.org/obo/CLO_0050989  KU812   LCL-1106
http://purl.obolibrary.org/obo/CLO_0051000  KU812E  LCL-1107
http://purl.obolibrary.org/obo/CLO_0050974  KU812F  LCL-1108
http://purl.obolibrary.org/obo/CLO_0050628  COLO-320    LCL-1174
http://purl.obolibrary.org/obo/CLO_0050632  LoVo    LCL-1181
http://purl.obolibrary.org/obo/CLO_0050698  G-361   LCL-1246
http://purl.obolibrary.org/obo/CLO_0050014  BeWo    LCL-1293
http://purl.obolibrary.org/obo/CLO_0051535  PC-3    LCL-1299
http://purl.obolibrary.org/obo/CLO_0050924  ME-180  LCL-1305
http://purl.obolibrary.org/obo/CLO_0050637  A172    LCL-1348
http://purl.obolibrary.org/obo/CLO_0050636  T98G    LCL-1357
http://purl.obolibrary.org/obo/CLO_0050011  A431    LCL-1404
http://purl.obolibrary.org/obo/CLO_0050810  HOS LCL-1421
http://purl.obolibrary.org/obo/CLO_0050808  MG-63   LCL-1428
http://purl.obolibrary.org/obo/CLO_0050140  Saos-2  LCL-1430
http://purl.obolibrary.org/obo/CLO_0051381  H-EMC-SS    LCL-1458
http://purl.obolibrary.org/obo/CLO_0050868  MCF7    LCL-1460
http://purl.obolibrary.org/obo/CLO_0050867  MDA-MB-453  LCL-1485
http://purl.obolibrary.org/obo/CLO_0050910  HeLa    LCL-1512
http://purl.obolibrary.org/obo/CLO_0051451  NIH:OVCAR-3 LCL-1522
http://purl.obolibrary.org/obo/CLO_0050930  Ca Ski  LCL-1541
http://purl.obolibrary.org/obo/CLO_0050025  A549    LCL-1601
http://purl.obolibrary.org/obo/CLO_0050949  8305C   LCL-1685
http://purl.obolibrary.org/obo/CLO_0050951  8505C   LCL-1686
http://purl.obolibrary.org/obo/CLO_0050845  5637    LCL-1702
http://purl.obolibrary.org/obo/CLO_0050843  T24 LCL-1709
http://purl.obolibrary.org/obo/CLO_0050102  PANC-1  LCL-1726
http://purl.obolibrary.org/obo/CLO_0050799  HGC-27  LCL-1882
http://purl.obolibrary.org/obo/CLO_0050971  CCRF-HSB-2  LCL-1914
http://purl.obolibrary.org/obo/CLO_0050856  Hep G2  LCL-1925
http://purl.obolibrary.org/obo/CLO_0008957  SC-1    LCL-1944
http://purl.obolibrary.org/obo/CLO_0050268  SK-N-SH LCL-1971
http://purl.obolibrary.org/obo/CLO_0050266  CHP-126 LCL-1973
http://purl.obolibrary.org/obo/CLO_0050081  PEER    LCL-2062

**Comment by chung88** [comment]
Hep G2 in Ontobee: LINCS-CLOview
Hep G2 cell in Ontobee: LINCS-CLOview
http://purl.obolibrary.org/obo/CLO_0003704 (CLO):
http://purl.obolibrary.org/obo/CLO_0050856 (CLO):
http://purl.obolibrary.org/obo/CLO_0050858 (CLO):

**Comment by yongqunh** [comment]
BALL-1 is processed, added: CLO_0037300. The other two are RIKEN cell lines.  

For Hep G2, the de fault becomes CLO_0003704. CLO_0050856 and CLO_0050858 are RIKEN cell line, CLO_0003713 is now obsolete.
