### ISSUE TITLE
OBO library points to CLO from 2013

### ISSUE THREAD

**Issue by cmungall** [CLO-ontology/CLO#38]
https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/clo.yml

```
products:
- clo.owl: https://raw.githubusercontent.com/CLO-ontology/CLO/master/src/ontology/clo_merged.owl
```

This is 4 years old! https://github.com/CLO-ontology/CLO/tree/master/src/ontology/release

This has multiple issues due to DOID changing so much, see https://github.com/monarch-initiative/dipper/issues/409

You should make a new merged file.

Additionally you should make a PURL for the unmerged one *and* make sure purls such as http://purl.obolibrary.org/obo/clo/DOID_import.owl resolve (you will need to create entries in the purl registry above)

**Comment by yongqunh** [comment]
A new version of CLO has been made.
