### ISSUE TITLE
"immortal human lung-derived epithelial cell line cell" misclassified

### ISSUE THREAD

**Issue by Tiepies** [CLO-ontology/CLO#44]
It looks like cells that should be members of the non-existent class "immortal human lung-derived epithelial cell line cell" are now classified under "immortal human septum of telencephalon-derived cell line cell" (obo:CLO_0000488), which is itself incorrectly asserted to be a subclass of "immortal human pancreas-derived cell line cell" (obo:CLO_0000551).

**Comment by yongqunh** [comment]
All the members under "immortal human septum of telencephalon-derived cell line cell" have now been assigned under other classes. Many are not related to lung. however, many others are related to skin or forskin. Other are related to breast. All cleaned up. Now the term "immortal human septum of telencephalon-derived cell line cell" has been obsolete (no cell line cells are really under such a definition).
