### ISSUE TITLE
Replace Deprecated ontology term EFO:0000887

### ISSUE THREAD

**Issue by FuqiX** [CLO-ontology/CLO#51]
Hi, 

The ontology term of "liver" in CLO was mapped to `EFO:000087`. However, this term has been deprecated and replaced by `UBERON_0002107`. Could you please update the ontology term accordingly?

Links:
Liver in CLO: https://www.ebi.ac.uk/ols/ontologies/clo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000887
Liver in EFO: https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_0000887
Liver in UBERON: http://purl.obolibrary.org/obo/UBERON_0002107

Thanks!

**Comment by yongqunh** [comment]
This is solved in the updated CLO.
