### ISSUE TITLE
Is CLO still maintained?

### ISSUE THREAD

**Issue by cmungall** [CLO-ontology/CLO#60]
I was answering a question on the cell ontology tracker https://github.com/obophenotype/cell-ontology/issues/832

it seems like something CLO should be able to answer. However it seemed like a ot of the terms were not present, and CLO has not been edited in >2 years. Is CLO still active?

**Comment by yongqunh** [comment]
@cmungall Somehow I have not seen your comment until now. Yes. CLO has been maintained. We are in the process of planning some big updates. I am now following the question in the CL tracker. Thanks.
