### ISSUE TITLE
rdf:type is typed as owl:AnnotationProperty

### ISSUE THREAD

**Issue by callahantiff** [CLO-ontology/CLO#62]
Hello!

I noticed that the property `rdf:type` has been typed as `owl:AnnotationProperty`:

```
    <!-- http://www.w3.org/1999/02/22-rdf-syntax-ns#type -->
    <owl:AnnotationProperty rdf:about="http://www.w3.org/1999/02/22-rdf-syntax-ns#type"/>
```

I believe that it should be typed as [`rdf:Property`](https://www.w3.org/1999/02/22-rdf-syntax-ns#type):

```
rdf:type a rdf:Property ;
	rdfs:isDefinedBy <http://www.w3.org/1999/02/22-rdf-syntax-ns#> ;
	rdfs:label "type" ;
	rdfs:comment "The subject is an instance of a class." ;
	rdfs:range rdfs:Class ;
	rdfs:domain rdfs:Resource .
```

Thank you! Including @matentzn given recent conversations 😄

**Comment by yongqunh** [comment]
It appears that the current version does not have this error any more.
