### ISSUE TITLE
Potentially Incorrect Typed RO Concepts

### ISSUE THREAD

**Issue by callahantiff** [CLO-ontology/CLO#63]
Hello!

The following Relation Ontology properties may be incorrectly typed as an `owl:AnnotationProperty`:

[`RO_0000087`](http://purl.obolibrary.org/obo/RO_0000087)
```
<!-- http://purl.obolibrary.org/obo/RO_0000087 -->
    <owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo/RO_0000087">
        <rdfs:range rdf:resource="http://purl.obolibrary.org/obo/BFO_0000023"/>
    </owl:AnnotationProperty>
```

[`RO_0002091`](http://purl.obolibrary.org/obo/RO_0002091)

```
    <!-- http://purl.obolibrary.org/obo/RO_0002091 -->
    <owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo/RO_0002091"/>
```

[`RO_0002222`](http://purl.obolibrary.org/obo/RO_0002222)

```
    <!-- http://purl.obolibrary.org/obo/RO_0002222 -->
    <owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo/RO_0002222"/>
```

Thank you! Tagging @matentzn given recent conversations 😄

**Comment by yongqunh** [comment]
This is solved with the updated CLO. Sorry for the delay. Thanks!
