### ISSUE TITLE
Cell is a child of cellular component?

### ISSUE THREAD

**Issue by zoependlington** [CLO-ontology/CLO#65]
Hello!

After running the [HCAO](https://github.com/ebi-ait/ontology) pipeline, we have noticed that cell (CL:0000000 - labelled cell_type in HCAO) is strangely a child of cellular_component (GO:0005575):

![image](https://user-images.githubusercontent.com/36990116/154522826-c8ccc8e2-65bf-4866-9bf8-dda8c853d9c3.png)

 After checking our import sources, we realised this comes from importing CLO:

![image](https://user-images.githubusercontent.com/36990116/154523053-09afceee-776b-469a-a6b4-9ba94e1c2512.png)

Also a note that the GO term for cell (GO:0005623) that is also in CLO is now obsoleted and may need to be updated too!

Thanks!

CCing to keep in loop: @paolaroncaglia

**Comment by paolaroncaglia** [comment]
Hi @yongqunh ,

We're aware that it may take some time before CLO can fix the issue above and do a new release (as per [this comment](https://github.com/CLO-ontology/CLO/issues/66#issuecomment-1049417980)). Could you please confirm if that's the case? Just so we know, and if necessary, we can assess and fix the issue on our end instead. 

Thank you for your work, and kind regards,

Paola Roncaglia (this is for the Human Cell Atlas application ontology)

**Comment by yongqunh** [comment]
These issues should be solved now. Sorry Please check out. Thanks.

**Comment by paolaroncaglia** [comment]
@yongqunh thank you!
