### ISSUE TITLE
mistakenly using realizes

### ISSUE THREAD

**Issue by linikujp** [CLO-ontology/CLO#8]
<a href="https://github.com/GoogleCodeExporter"><img src="https://avatars.githubusercontent.com/u/9614759?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [GoogleCodeExporter](https://github.com/GoogleCodeExporter)**
_Tuesday May 12, 2015 at 11:44 GMT_
_Originally opened as https://github.com/linikujp/clo-ontology/issues/8_

---

```
In current CLO, there are two assertions as such:

'adherent cell line culturing' subClassOf: realizes some 'adherent cell culture 
growth mode'
'suspension cell line culturing' subClassOf: realizes some 'suspension cell 
culture growth mode'

The two cell line culturing classes can't be subClassOf realizes some ??? mode.
Since the 'adherent cell culture growth mode' and 'suspension cell culture 
growth mode'are subclasses of quality.
The range of realizes must be 'realizable entity'. Quality is disjoint with 
'realizable entity'. So the above assertion will make the ontology inconsistent.

Solution: Change 'realizes' into 'has_quality'.

```

Original issue reported on code.google.com by `linik...@gmail.com` on 2 Jun 2014 at 10:07

**Comment by linikujp** [comment]
<a href="https://github.com/GoogleCodeExporter"><img src="https://avatars.githubusercontent.com/u/9614759?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GoogleCodeExporter](https://github.com/GoogleCodeExporter)**
_Tuesday May 12, 2015 at 11:44 GMT_

----

```
We can't change realizes into has_quality, since the domain of has_quality must 
be independent continuent, and the two cell line culturing are processes.
We may need to change the growth mode to another subclass.
```

Original comment by `linik...@gmail.com` on 2 Jun 2014 at 10:12

**Comment by yongqunh** [comment]
They have been changed to disposition.
