### ISSUE TITLE
RPMI 6666 cell line contamination according to ICLAC

### ISSUE THREAD

**Issue by linikujp** [CLO-ontology/CLO#9]
<a href="https://github.com/GoogleCodeExporter"><img src="https://avatars.githubusercontent.com/u/9614759?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [GoogleCodeExporter](https://github.com/GoogleCodeExporter)**
_Tuesday May 12, 2015 at 11:44 GMT_
_Originally opened as https://github.com/linikujp/clo-ontology/issues/9_

---

```
See: http://iclac.org/wp-content/uploads/Cross-Contaminations-v7_2.pdf

This information should be integrated with CLO.

The comment for CLO:0008870 is 'disease: Hodgkins disease' (no axioms)

According to iclac, the cell type is EBV+ B-lymphoblastoid

```

Original issue reported on code.google.com by `cmung...@gmail.com` on 19 Oct 2014 at 1:52

**Comment by yongqunh** [comment]
Updated: http://purl.obolibrary.org/obo/CLO_0008870
